### ISSUE TITLE
Adding examples to parameters and schemas

### ISSUE THREAD

**Issue by williamdias** [zhandao/zero-rails_openapi#17]
Hi, 

Is it possible to add an example to a field in a schema? I was not able generate a json file that looks similar to the ones described here: https://swagger.io/docs/specification/adding-examples/#schemas

In the snippet below, I would like to add an example to the medium_id field.

```ruby 
components do
  schema :medium => [
    {
      medium_id: { type: 'string', desc: 'the medium id; ex: 1577754239923912471_357658764' },
    },
    desc: 'medium record'
  ]
end
```

What about examples in parameters? (https://swagger.io/docs/specification/adding-examples/#parameters)

Thanks!

**Comment by zhandao** [comment]
Hi, you can currently use `examples`, and it is [**multiple**](https://swagger.io/docs/specification/adding-examples/#parameters).
```
medium_id: {
  type: 'string', desc: 'the medium id', examples: { foo: '1577754239923912471_357658764' }
}
```

**Comment by williamdias** [comment]
Hi, @zhandao. Thanks for your reply.

When I use the syntax you provided in a schema field, on the Swagger-ui, I get:

**Example value**
```
[
  {
    "medium_id": "string",
  }
}
```
**Model**
```

medium_id | string
          | examples: List [ OrderedMap { "foo": OrderedMap { "value": "1577754239923912471_357658764" } } ]
          | the medium id
```
On the other hand, when I edit the generated json file and add the `example` keyword
```
"medium_id": {
  "type": "string",
  "description": "the medium id",
  "example": "1577754239923912471_357658764"
}
```

I get:

**Example value**
```
[
  {
    "medium_id": "1577754239923912471_357658764",
  }
]
```
**Model**
```
medium_id | string
          | example: 1577754239923912471_357658764
          | the medium id
```

When adding the `examples` keyword to parameters, the result is similar.

Any chance to add the singular `example` keyword?

**Comment by zhandao** [comment]
@williamdias OK, I will do it.

**Comment by zhandao** [comment]
Done. Try it like [this](https://github.com/zhandao/zero-rails_openapi/commit/20c20b77eca868ac35c110cffdcb872cc559a282#diff-917ffdde79050994c60fead0486d60fcR197).

**Comment by williamdias** [comment]
Great job, @zhandao. Thank you!

**Comment by zhandao** [comment]
:)
