### ISSUE TITLE
Multiple components blocks

### ISSUE THREAD

**Issue by Amnesthesia** [zhandao/zero-rails_openapi#18]
I want to separate components into multiple files without duplicating them, so I have some modules that define response_refs and param_refs, and then I include these helpers.

It seems like only the last `components do ... end` will be evaluated, and all the ones before will be *overwritten*.

Is there a way I can define components in multiple files?

**Comment by zhandao** [comment]
Thank you, it's a bug. I'll fix it.

**Comment by Amnesthesia** [comment]
For example, if you have something like this:

```ruby
module Version1::OpenApi::ModelAResponses
   def self.included(base)
      base.components do
           response :SingleModelA => ['success', :json, data: {
              field: { type: String, desc: 'Test' }
           }]

          response :ListModelA => ['success', :json, data: {
              data: [{ field: { type: String, desc: 'Test' } }]
           }]
       end
   end
end
```

and another module

```ruby
module Version1::OpenApi::ModelBResponses
   def self.included(base)
      base.components do
           response :SingleModelB => ['success', :json, data: {
              field: { type: String, desc: 'Test' }
           }]

           response :ListModelB => ['success', :json, data: {
              data: [{ field: { type: String, desc: 'Test' } }]
           }]
       end
   end
end
```

and in your BaseController, you do something like:

```ruby
class Version1::BaseController < ApplicationController
    Version1::OpenApi::ModelAResponses
    Version1::OpenApi::ModelBResponses
end
```

**This will not work, :ListModelA will not be defined because Version1::OpenApi::ModelAResponses was not the last included module, and Version1::OpenApi::ModelBResponses redefines components** 
```ruby
class Version1::ModelAController < Version1::BaseController

   api :index, 'List model A' do
       response_ref 200 => :ListModelA. # This does not exist now
   end
   def index
      # ....
   end
end
```

But this will work:

```ruby
class Version1::ModelBController < Version1::BaseController

   api :index, 'List model B' do
       response_ref 200 => :ListModelB. # This exists
   end
   def index
      # ....
   end
end
```

The .json schema generated will *only* contain components defined in `Version1::OpenApi::ModelBResponses` or whatever is the last included module.

**Comment by zhandao** [comment]
Please update this gem and try again. 😄

**Comment by zhandao** [comment]
Is there any problem?

**Comment by Amnesthesia** [comment]
Thank you @zhandao! I will try it out tonight and tell you how it went :-) 

Appreciate the quick response!

**Comment by zhandao** [comment]
Hi, should I finish this issue? @Amnesthesia
