### ISSUE TITLE
Generating OpenAPI fails with Spring

### ISSUE THREAD

**Issue by Amnesthesia** [zhandao/zero-rails_openapi#19]
To reproduce:

1. Run `OpenApi.write_docs` in rails console
2. Make some changes to your specification and reload console
3. Run `OpenApi.write_docs` again.

Now, you will either 1) Get no `paths` in your schema, or 2) only get *some* components.

Solution: 
- `spring stop` and run `OpenApi.write_docs` again.
- **or** you can change the "homepage" key to another key in the `initializers/openapi.rb` file, and it will also work.

I think **maybe** it's because of the bang in https://github.com/zhandao/zero-rails_openapi/blob/f5a83abe14bed15746effca645afce96b1b70556/lib/open_api/generator.rb#L23 which maybe causes Config.docs['homepage'] to be overwritten, so the next time it tries to generate, this is not properly configured anymore?

**Comment by zhandao** [comment]
Thank you, I tried and found that the problem happened in https://github.com/zhandao/zero-rails_openapi/blob/master/lib/open_api/generator.rb#L36
After change specification and reload console, `puts settings[:base_doc_class].descendants` will be an empty array. (The generator get all specification declarations by all of their class constants.)
I think this problem may be related to Rails reloading.

**Comment by Amnesthesia** [comment]
I'm not sure, but I think because you use the `merge!` bang method in the `reduce` call, you may be modifying one of the original elements, causing it to not reduce properly next time, on line #23. For example:

```ruby
irb(main):019:0> a = { one: "one" }
=> {:one=>"one"}
irb(main):020:0> b = { two: "two" }
=> {:two=>"two"}
irb(main):021:0> c = { three: "three" }
=> {:three=>"three"}
irb(main):022:0> [a, b, c].reduce(&:merge)
=> {:one=>"one", :two=>"two", :three=>"three"}
irb(main):023:0> a
=> {:one=>"one"}

# Same thing but without bang
irb(main):024:0> [a, b, c].reduce(&:merge!)
=> {:one=>"one", :two=>"two", :three=>"three"}
irb(main):025:0> a
=> {:one=>"one", :two=>"two", :three=>"three"}
irb(main):026:0> b
=> {:two=>"two"}
```

Since you only use the return value, maybe you don't need the bang?

**Comment by Amnesthesia** [comment]
That's very strange, isn't it? Isn't `require` synchronous? 

I don't think `sleep(0.1.seconds)` is a good solution because there's no magic number that will always work, there must be a better way to know if re-require has finished

**Comment by zhandao** [comment]
Solution: Are you using `doc_location` in the setting? You may use the following way to replace it:
```ruby
# config/application.rb
Dir['path/to/spec'].each { |path| config.autoload_paths << path }
```

Then, re-require will be done while Rails reloading.

**Comment by zhandao** [comment]
@Amnesthesia Yes, I will not commit this way.

**Comment by Amnesthesia** [comment]
No, I'm not using `doc_location`, just `base_doc_class`

**Comment by zhandao** [comment]
Do you write specification in controllers?

**Comment by Amnesthesia** [comment]
I write the `api ... do .. end` blocks in the controllers, but I keep the `components` blocks in concerns

**Comment by zhandao** [comment]
To solve this problem, the solution now I can think of is to add your spec class (controller) paths to `autoload_paths`.

But why isn't `require` synchronous, and how to know if re-require has finished, should also try to figure it out. It's really strange.

**Comment by Amnesthesia** [comment]
@zhandao What I'm thinking is that, if you try to require something twice in console, the second time you will get `false`, because it was already loaded — maybe you can force re-load it using `load` if require returns false

**Comment by akram71093** [comment]
@zhandao did you find any solution to this problem ?

**Comment by ralfizzle** [comment]
Was there any update on this?
