### ISSUE TITLE
Document Associative Arrays

### ISSUE THREAD

**Issue by barnaclebarnes** [zhandao/zero-rails_openapi#21]
To output this:

```
name: {
  "en": "The Broad"
  "de": "De Broad"
}
```

We should be using a [Dictionaries, HashMaps and Associative Arrays](https://swagger.io/docs/specification/data-models/dictionaries/)

This uses the `additionalProperties` but deifning this doesn't seem to work:

`name: {type: Object, additionalProperties: String}`

Outputs

```
"name": {
  "type": "object"
}
```

But should output (I think):

```
"name": {
  "type": "object"
  "additionalProperties" {
    "type": "string"
  }
}
```

**Comment by zhandao** [comment]
This specification has not been supported yet, I'll update later if you need. @barnaclebarnes

**Comment by barnaclebarnes** [comment]
@zhandao That would be great. We are using this in quite a few places where were have translated fields. Now that I am starting to get my head around how this all works I'm loving it. Thanks!

**Comment by zhandao** [comment]
Hi, please update this gem from GitHub, and try it like https://github.com/zhandao/zero-rails_openapi/commit/f330d416b42a6ae0449a94bebb484d178a49cd73#diff-917ffdde79050994c60fead0486d60fcR211

Here are two ways to define this specification:
1. Use the keywords: `additional_properties`, `add_prop`, or values_type`.
2. Use `{ type: '{=>integer}' }` instead of `{ type: Object }`.

**Comment by barnaclebarnes** [comment]
I think I have the additionalProperties outputting as per the proper spec but I think there is a bug in that every item now has ` "additionalProperties": { "type": "string"}` added to the end of it. 

```
api :show, 'This API gets the top level app metadata' do
  response '200', 'success', :json, data: {
    name: {type: '{=>string}' }, additionalProperties: { type: 'string'}
  }
end
```

```
      "/api/v3/app": {
      "get": {
        "summary": "This API gets the top level app metadata",
        "operationId": "show",
        "tags": [
          "Apps"
        ],
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": {
                    "type": ""
                  }
                }
              }
            }
          }
        }
     
```

**Comment by zhandao** [comment]
```ruby
data: {
    name: { type: '{=>string}' }, 
    additionalProperties: { type: 'string'}
}
```
Means that TWO fields in your form data body -- "name" and "additionalProperties".

```ruby
"additionalProperties": {
    "type": ""
}
````
is a bug, I had fixed it.

**Comment by zhandao** [comment]
```ruby
data: {
    name: { type: '{=>string}' }, 
}
# or
data: {
    name: { type: Object, additional_properties: 'string' }
}
```

**Comment by barnaclebarnes** [comment]
All seems to work now.
