### ISSUE TITLE
operationID not unique

### ISSUE THREAD

**Issue by barnaclebarnes** [zhandao/zero-rails_openapi#23]
The `operationId` being output is currently the [action name](https://github.com/zhandao/zero-rails_openapi/blob/57d12c3fed19f6712f695d1644a9039a0992105a/lib/open_api/dsl.rb#L44) of the controller. [According to the docs](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#documentStructure):

"operationId: string - Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions."

As multiple controllers may have  `index`, `show` methods, etc. then this outputs duplicate `operationID`'s. It would be good if:

1. The default was `#{controller_name}_#{action}`
2. You could set this in the `api` call

**Comment by barnaclebarnes** [comment]
I realised I can do `self[:operationId] = "show_app"` in the `api` block so no need for number 2 on that list. 1 though should default to creating a unique name.

**Comment by zhandao** [comment]
You're right, I will consider that.

**Comment by zhandao** [comment]
Hi, I updated the changes.
Number 1 became the default, and you can do number 2 by the param keyword `id` of the `api` method, like: `api :index, id: :show_all, ...`

Thanks you.

**Comment by barnaclebarnes** [comment]
@zhandao Thanks for that. I would potentially make it like this to make it bit nicer to read:

```
# ControllerNameAction
"#{@doc_info[:tag][:name]}#{action.capitalize}"
```

Not a critical though.

**Comment by zhandao** [comment]
OK, I'll make that in next commit.

**Comment by zhandao** [comment]
Done.
