### ISSUE TITLE
Cannot define schema for simple Hash

### ISSUE THREAD

**Issue by ocha** [zhandao/zero-rails_openapi#24]
I am trying to define a schema for a semi-complex Object. But I am running into issue trying to define individual fields for it.
For example given a Hash for User which I want to define schema for
```
{
name: "John", 
permissions: ["READ", "WRITE"], 
contact: { email: "john@smith.com", phone: "234-234-2344" }
}
```

I tried using `components` block with `schema :User => [ ...many different variations...]` but all I got in json output was
```
    "schemas": {
       "User": {
         "type": "object"
       }
     }
```

Is there an example how to define schema for a Hash?

**Comment by zhandao** [comment]
Hi, please see [`advance usage` of point 2](https://github.com/zhandao/zero-rails_openapi#dsl-methods-inside-componentss-block-code-source).

**Comment by zhandao** [comment]
Hi @ocha , any questions?

**Comment by ocha** [comment]
thanks @zhandao . It worked. I was missing `desc: 'foo'` field. If I remove that field, I dont get schema generated at all. Is `desc` intended to be required field?

**Comment by zhandao** [comment]
No ... Could you show me your code?

**Comment by ocha** [comment]
without `desc`, code below doesnt generate schema.
```
class V1::FooDoc < ApiDocV1
  route_base "api/v1/foos"

  components do
    schema :Foo => [
      {
        foo: {
          id: String
        },
        page: String
      }
    ]
  end
end

**Comment by zhandao** [comment]
Oh I see, a small bug causes it to be different from expectations.

Currently, it will also work:
```ruby
schema :Foo => [{ your Object type field's schema }, {}]
```

**Comment by zhandao** [comment]
update: code below also OK.
```
schema :Foo => { type: { foo: ..., page: ... } }
```
