### ISSUE TITLE
Use of "&." requires Ruby 2.3

### ISSUE THREAD

**Issue by smeeks** [zhandao/zero-rails_openapi#30]
We tried using zero-rails_openapi in our project but it fails on the instances of the "&." operator in generator.rb because our project is still using Ruby 2.2. Would you consider adding a s.required_ruby_version = '>= 2.3' to the gemspec to make the required version explicit?

**Comment by zhandao** [comment]
OK, I'll do that.

You can also make some monkey patches like this, if you want to use it in Ruby 2.2:
```
module OpenApi
  module Generator
	module_function
	
	def get_actions_by_route_base(route_base)
	  return unless routes_list[route_base]
      routes_list[route_base].map do |action_info|
        action_info[:action_path].split('#').last
      end
    end
  end
end
```
