### ISSUE TITLE
Duplicate operationId's

### ISSUE THREAD

**Issue by barnaclebarnes** [zhandao/zero-rails_openapi#32]
When generating the docs the `operationId` is not unique for `PUT` and `PATCH`

So:

```
api(:update, "Update a single Collection") do
 ...
```

Generates both: 

```
      "put": {
        "summary": "Update a single Collection",
        "operationId": "Collections_update",

```

and:

```
"patch": {
        "summary": "Update a single Collection",
        "operationId": "Collections_update",
```

Which throws errors in the code gen tool:

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 4, Warning count: 0
Errors:
	-attribute paths.'/api/frontend_v2/user'(patch).operationId is repeated
	-attribute paths.'/api/frontend_v2/screens/{id}'(patch).operationId is repeated
	-attribute paths.'/api/frontend_v2/collections/{id}'(patch).operationId is repeated
	-attribute paths.'/api/frontend_v2/media_items/{id}'(patch).operationId is repeated
```

Not sure how to get around this?

**Comment by zhandao** [comment]
But how to define `operation`?
Should an `operation` correspond to a controller action, or URL + HTTP method?

**Comment by barnaclebarnes** [comment]
So the issue here is that you are currently defaulting to the controller action which works most of the time but does not work for `update` as that generates both a `PUT` and a `PATCH` method. Also if you supply a custom name for the endpoint there needs to be a way to define a name that is unique:

`api(:update, "Update a single Collection", id: "CollectionUpdate")`

Something like this would work I guess but a bit convoluted:

`api(:update, "Update a single Collection", id: "CollectionUpdate#{method}")`

**Comment by zhandao** [comment]
You can try to define an API by specifying `http`, and at the same time specify its `id`, like:

```ruby
definition = -> { form data: { } }
api :update, 'summary', http: :patch, id: :update_via_patch, &definition
api :update, 'summary', http: :put, id: :update_via_put, &definition
```

(But I haven't tried that yet)

**Comment by barnaclebarnes** [comment]
That works but you have to put the verb in quotes, not a symbol `"patch"` instead of `:patch`

**Comment by zhandao** [comment]
👌
