### ISSUE TITLE
ReDoc Vendor Extensions

### ISSUE THREAD

**Issue by drjonnicholson** [zhandao/zero-rails_openapi#38]
I'm working on getting  a spec generated with your tool to work nicely in ReDoc. Only problem I have is in the difficulty of getting some of the vendor extensions to be included in the spec - ideally this library should allow vendor extensions to be passed through. 

Specifically, I need to use `x-logo`, `x-tagGroups` and `x-displayName` from here:
https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md

`x-logo` is easy as it can be added straight to the `info` DSL, e.g.:

```Ruby
info version: '1.0.0',
       title: 'Fake API',
       'x-logo': { url: BASE64_ENCODED_OR_URL, altText: 'ALT TEXT' },
...
```

`x-tagGroups` I've managed to add by injecting them to the generated document's hash before we render to JSON, which isn't pretty but it works. Something like this:

```Ruby
data = OpenApi.generate_docs
doc = data[:SPEC_IDENTIFIER]
doc[:'x-tagGroups'] = xTagGroupsHash
json = JSON.generate(doc)
```

`x-displayName` is the one that appears to be completely blocked by the code. Basically I'm doing something like this:

```Ruby
doc_tag name: tag, desc: I18n.t(tag.underscore), 'x-displayName': tag.titleize
```

But I get a `unknown keyword: x-displayName` error. I've also tried doing `externalDocs` as documented, but that fails in the same way. Any help on this/working around it would be great!

**Comment by zhandao** [comment]
Upgrading to the latest version will solve this.

(`desc: ` should be changed to `description: `)

**Comment by drjonnicholson** [comment]
👍 Yup that fixed it! Thanks!

**Comment by zhandao** [comment]
👍
