### ISSUE TITLE
Help with descriptions in schemas

### ISSUE THREAD

**Issue by drjonnicholson** [zhandao/zero-rails_openapi#40]
I'm having trouble getting properties in schemas to have descriptions. When I call `schema` I pass a name and a hash as the type.

Something a bit like this:
```Ruby
definition = {
  email: {
    id: 'Integer',
    email: 'String',
    type: 'String',
    is_primary: 'Boolean'
  }
}

schema(Email, definition, desc: 'An email')
```

Looking at https://github.com/zhandao/zero-rails_openapi/blob/master/lib/oas_objs/schema_obj_helpers.rb#L8 I should be able to add descriptions to each property, but I can't get it to work.

What do i have to do to give properties in a schema object a description?

**Comment by zhandao** [comment]
Is the description `An email` for the Schema Object `Email`, or each property of `Email`?

**Comment by zhandao** [comment]
What is the generated JSON like?

**Comment by drjonnicholson** [comment]
I'd basically like to end up with something like this:

```JSON
"Email": {
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "An ID"
    },
    "email": {
      "type": "string",
      "description": "The email address iteslf"
    },
    "type": {
      "type": "string",
      "description": "Kind of email, e.g. home or work"
    },
    "is_primary": {
      "type": "boolean",
      "description": "Whether this is the main email to use"
    }
  },
  "description": "An email address."
},
```

But I can only appear to get this:

```JSON
"Email": {
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "email": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "is_primary": {
      "type": "boolean"
    }
  },
  "description": "An email address."
},
```

**Comment by zhandao** [comment]
Use schema hash to define each property:
```ruby
schema Email, {
     id: { type: Integer, desc: 'An ID' },
  email: { type: String, desc: 'The email address iteslf' }
}, desc: 'An email'
```
For more examples: [(2) schema](https://github.com/zhandao/zero-rails_openapi#dsls-written-inside-componentss-block)

**Comment by drjonnicholson** [comment]
So if I do this

```Ruby
schema Email => [ { id: { type: 'Integer', desc: 'An ID' } } ]
```

Then I get the error `OpenApi Syntax Error: param `Email` has no schema type!`

If I change it to this:

```Ruby
schema Email => [ { type: 'Object', id: { type: 'Integer', desc: 'An ID' } } ]
```

I get this output:

```JSON
"Email": {
  "id": {
    "type": "Integer",
    "desc": "An ID"
  }
},
```

But it should look like this:

```JSON
"Email": {
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "An ID"
    }
  }
},
```

What appears needed is this:

```Ruby
schema Email => [ { 'id' => { type: 'Integer', desc: 'An ID' } } ]
```

So, the issue is that the `type` and `desc` properties need to be symbols, everything else must be addressed by a string

**Comment by drjonnicholson** [comment]
That's on version 2.0.3. What I'm not sure is if that's a bug or a feature.

We load our definitions from a YAML file, so it looks like I either need to change how we load definitions, or I have to walk each definition hash and symbolize the keys of any hash which only have the keys `type` and `desc` (or any predefined set I guess, if we include example etc). The potential for collision with intentionally named object properties is a little scary.

**Comment by zhandao** [comment]
Let's see the method signature of `schema`:
```ruby
schema component_key, type = nil, **schema
```
`type` is optional, so if you:
```ruby
schema :Key, { id: String }
```
It actually makes `schema == { id: String }`, but not `type`.

Have a try like this?
```ruby
schema Email => [ { id: { type: 'Integer', desc: 'An ID' } }, { } ]
# or
schema Email => [ type: { id: { type: 'Integer', desc: 'An ID' } } ]
```

**Comment by zhandao** [comment]
> That's on version 2.0.3. What I'm not sure is if that's a bug or a feature.
> 
> We load our definitions from a YAML file, so it looks like I either need to change how we load definitions, or I have to walk each definition hash and symbolize the keys of any hash which only have the keys `type` and `desc` (or any predefined set I guess, if we include example etc). The potential for collision with intentionally named object properties is a little scary.

How did you write it before?

**Comment by drjonnicholson** [comment]
I'm adding the descriptions, so we didn't have it before :)

Right, this is the solution:

Th definitions loaded from a YAML file need to have `deep_symbolize_keys` run on it, and the `schema Thing => [ type: definition ]` syntax works a charm!

**Comment by drjonnicholson** [comment]
Thanks @zhandao

**Comment by zhandao** [comment]
You are welcome ~
