### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by drjonnicholson** [zhandao/zero-rails_openapi#42]
Hi again @zhandao .

I'm trying to add paging related headers to responses. I've looked at https://github.com/zhandao/zero-rails_openapi/blob/master/lib/open_api/dsl/api.rb#L98, and see additional options can be passed. But the way these are handled force the additional hash into the content (https://github.com/zhandao/zero-rails_openapi/blob/master/lib/oas_objs/response_obj.rb#L20).

Would it be possible to add support for headers, or let me know of a work around please? Thanks!

**Comment by zhandao** [comment]
Hi, new version 2.1.0 supports defining header (Header Object) in response.

Example:
https://github.com/zhandao/zero-rails_openapi/blob/f1a76238c65acdedce8e3808a8ca42b7528fac41/spec/api_spec.rb#L191

PR: [#43](https://github.com/zhandao/zero-rails_openapi/pull/43)

**Comment by drjonnicholson** [comment]
Fantastic! Thanks for the quick update!

**Comment by zhandao** [comment]
😄
