### ISSUE TITLE
Response properties named type cause problems

### ISSUE THREAD

**Issue by drjonnicholson** [zhandao/zero-rails_openapi#50]
In our specification we have a definition of an email, which has in it a property called `type`. This appears to cause hell in the generated spec.

A minimal example would be something like this::

```Ruby
schema :EmailSchema => [ 
  { 
    type: { 
      email: { type: String, desc: 'The email'}, 
      type: { type: String, desc: 'work/home' }
    },
    desc: 'an email object'
  }
]
```

This produces:

```JSON
"EmailSchema": {
  "type": "string",
  "email": {
    "type": "String",
    "desc": "The email"
  },
  "description": "an email object"
}
```

But it should produce something like:

```JSON
"EmailSchema": {
  "type": "object",
  "properties": {
    "email": {
      "type": "String",
      "desc": "The email"
    },
    "type": {
      "type": "String",
      "desc": "work/home"
    },
  }
  "description": "an email object"
}
```

Any thoughts?

**Comment by zhandao** [comment]
Try to stringify the prop key `type`:

```ruby
schema :EmailSchema => [ 
  { 
    'type' => { 
      email: { type: String, desc: 'The email'}, 
      'type' => { type: String, desc: 'work/home' }
    },
    desc: 'an email object'
  }
]
```

**Comment by drjonnicholson** [comment]
I can have a play with how we read in / construct the definitions object before passing them to your lib and see. So to confirm you are suggesting stringifying ‘type’ keys where the value is an other hash, and leaving them as symbols where the value is a primitive?

Interested to ask, is that intended behaviour in the lib, or is it a bit of a hack that happens to work?

**Comment by zhandao** [comment]
In this lib, The **symbolize** word `type` is a reserved "keyword".

The definition hash you pass to the method `schema` (or param / response ...) will be processed (extract the real OAS schema type) by [this method](https://github.com/zhandao/zero-rails_openapi/blob/master/lib/open_api/dsl/helpers.rb#L35), and then initialize a [`SchemaObj`](https://github.com/zhandao/zero-rails_openapi/blob/master/lib/oas_objs/schema_obj.rb).

In addition, "nested schema type" also [extract](https://github.com/zhandao/zero-rails_openapi/blob/master/lib/oas_objs/schema_obj_helpers.rb#L12) the real schema type recursively.

**Comment by zhandao** [comment]
Close it?

**Comment by drjonnicholson** [comment]
Yup, thanks @zhandao !

In case anyone else stumbles on this with the same issue, I solved it with something a bit like this:

```Ruby
  TYPE_KEYS = %w[type desc example examples].to_set.freeze
  
  def symbolize_keys(definition)
    case definition
    when Array
      definition.map { |v| symbolize_keys(v) }
    when Hash
      definition.each_with_object({}) do |(k, v), h|
        k = k.to_sym unless k == 'type' && v.is_a?(Hash) && v.keys.to_set.subset?(TYPE_KEYS)
        h[k] = symbolize_keys(v)
      end
    else
      definition
    end
  end
```

where `definition` is the value read out of the YAML file and `TYPE_KEYS` needs updating to include any other properties (e.g. extensions) that might appear in those particular `type` properties to be managed differently.
