### ISSUE TITLE
NoMethodError: undefined method `oas' for ApplicationResource:Class

### ISSUE THREAD

**Issue by amitdotagarwal** [zhandao/zero-rails_openapi#51]
[2] [iam][development][development] pry(main)> OpenApi.write_docs
NoMethodError: undefined method `oas' for ApplicationResource:Class
from /Users/amitagarwal/.rvm/gems/ruby-2.6.0/gems/zero-rails_openapi-2.1.0/lib/open_api.rb:37:in `block in generate_doc'
[3] [iam][development][development] pry(main)>

**Comment by zhandao** [comment]
Do you include the DSL?

https://github.com/zhandao/zero-rails_openapi#first-of-all-include-openapidsl-in-your-base-class-which-is-for-writing-spec
