### ISSUE TITLE
additional_properties: true not generating correct doc

### ISSUE THREAD

**Issue by bopm** [zhandao/zero-rails_openapi#55]
I have next definition:
```
schema FreeFormObj: {
  type: Object,
  additional_properties: true
}
```
I wait it to generate next valid doc:
```
"FreeFormObj": {
  "type": "object",
  "additionalProperties": true
}
```
but instead, it generates invalid one:
```
"FreeFormObj": {
  "type": "object",
  "additionalProperties": {
    "type": "true"
  }
}
```

**Comment by zhandao** [comment]
`additionalProperties` should be a [SchemaObject](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#schema-object).

`true` is invalid.

**Comment by bopm** [comment]
No it's not, according to https://swagger.io/specification/ :

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

Also:  https://github.com/OAI/OpenAPI-Specification/issues/668#issuecomment-281837896

`True` means that definition is open ended. Any property can be added. I am using doc to generate ruby client with `openapitools/openapi-generator` and it's handling `true` value like it supposed to. But now I need to manually replace code generated with gem to correct format.

**Comment by zhandao** [comment]
Oh, sorry. I'll fix it.

**Comment by bopm** [comment]
Not a problem, thanks for all your work!

**Comment by zhandao** [comment]
New version released 😄
