### ISSUE TITLE
Fusion not working when using multiple body_ref

### ISSUE THREAD

**Issue by callard42** [zhandao/zero-rails_openapi#57]
I am trying to use components for my body request, but it seems to not fusion them and just take the last component mentioned. If I don't use the components and use directly multiple request_body it works fine.

Here it works:
 ```ruby
api :create_application, 'Create Application' do
request_body :opt, :form, data: {
    profiles_params: {
      type: {
        Id!: { type: Integer, desc: 'Id'},
        age: { type: Integer, desc: 'Age' },
      },
      desc: 'Profiles Parameters'
    }
  }
  request_body :opt, :form, data: {
    application_params: {
      type: {
        # user
        first_name: { type: String, desc: 'First Name' },
        last_name: { type: String, desc: 'Last Name' },
      },
      desc: 'Application Parameters'
    },
  }
end
```

And here it doesn't, only ApplicationParams will be used:
```ruby
components do
  request_body :ProfileParams, :opt, :form, data: {
    profiles_params: {
      type: {
        Id!: { type: Integer, desc: 'Id'},
        age: { type: Integer, desc: 'Age' },
      },
      desc: 'Profiles Parameters'
    }
  }
  request_body :ApplicationParams, :opt, :form, data: {
    application_params: {
      type: {
        # user
        first_name: { type: String, desc: 'First Name' },
        last_name: { type: String, desc: 'Last Name' },
      },
      desc: 'Application Parameters'
    },
  }
end

api :create_application, 'Create Application' do
  body_ref :ProfileParams
  body_ref :ApplicationParams
end
```

It is normal behavior that fusion doesn't work for body refs or is there a syntax/workaround I haven't found ?

Also, the alias 'body' cannot be used to declare a component, I get a ' wrong number of arguments (given 3, expected 2)' error. Just wanted to note that since I struggle with it for a while.

Thanks!

**Comment by zhandao** [comment]
> only ApplicationParams will be used

Yes, this is expected behavior:  
https://github.com/zhandao/zero-rails_openapi/blob/master/lib/open_api/dsl/api.rb#L75

Because in the [OAS 3.0](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#fixed-fields-19), `$ref` Object is type `String`, it links to the specified **named** component, fusion named components into "anonymous" components is not allowed.

To slove it (DRY your code?), you can do something like this:
```ruby
ProfileParams = {
     profiles_params: {
       type: {
         Id!: { type: Integer, desc: 'Id'},
         age: { type: Integer, desc: 'Age' },
       },
       desc: 'Profiles Parameters'
     }
   }
ApplicationParams = {
     application_params: {
       type: {
         first_name: { type: String, desc: 'First Name' },
         last_name: { type: String, desc: 'Last Name' },
       },
       desc: 'Application Parameters'
     },
   }

api :api1, 'API 1' do
  request_body :opt, :form, data: {**ProfileParams, **ApplicationParams}
end

api :api2, 'API 2' do
  request_body :opt, :form, data: ProfileParams
end

components do
  request_body :ProfileParams, :opt, :form, data: ProfileParams
  request_body :ApplicationParams, :opt, :form, data: ApplicationParams
end
```

**Comment by zhandao** [comment]
> the alias 'body' cannot be used to declare a component, I get a ' wrong number of arguments (given 3, expected 2)' error

1. Ruby version?
2. Your usage?
3. Error stack?

thanks.

**Comment by zhandao** [comment]
Hi, is there any problem?

**Comment by callard42** [comment]
I am on ruby 2.4.6p354 (2019-04-01 revision 67394)

The error happened when using alias *body* instead of *request_body* to declare a component
for ex:
```
components do
  body :ProfileParams, :opt, :form, data: {
    profiles_params: {
      type: {
        Id!: { type: Integer, desc: 'Id'},
        age: { type: Integer, desc: 'Age' },
      },
      desc: 'Profiles Parameters'
    }
  }
end
api :create_application, 'Create Application' do
  body_ref :ProfileParams
end
```
It seems that the component_key is one parameter too much for this use of alias body. 

I have found a workaround that works for me without using components so it is not a problem for me, just wanted to let you know.

Thanks

**Comment by zhandao** [comment]
Hi, the signature of `request_body` inside `components` is:  
`component_key, required, media_type, data: { }, desc: '', **options`  

the signature of `body` / `body!` is:  
`component_key, media_type, data: { }, **options`

The second parameter `required` of `request_body` does not exist in `body(!)`, **the bang(!) method** means that it is **required**.
