### ISSUE TITLE
config option for additionalProperties on false by default

### ISSUE THREAD

**Issue by remuspoienar** [zhandao/zero-rails_openapi#61]
Hi, 

Thanks for writing this library !

Got used to most of the DSLs provided and was wondering if there is a way to configure **additionalProperties** to be implicitly **false** on all schemas/subschemas if not specified.

I'd like to be able to either configure it globally in the configuration file or in a schema object and have it applied on all schemas that are nested.

**Comment by zhandao** [comment]
The code to handle `additionalProperties` is: https://github.com/zhandao/zero-rails_openapi/blob/master/lib/oas_objs/schema_obj.rb#L58

Do you mean, when additionalProperties is not specified, this line of code returns a `{ additionalProperties: false }`? (And the behavior is configurable?)

**Comment by remuspoienar** [comment]
Yes, that is indeed the behaviour i would like, since in OAS3 additionalProperties is true by default. And i think this should be configurable, since it is not desirable for everyone that uses the library. I use  api response validation in tests based on the swagger definition, and i want my tests to fail if new fields are added (when additionalProperties is false in the definition) or removed(when fields are required in the definition).
So adding additionalProperties: false on every schema and nested schemas inside will greatly bloat my code, since its always the same value on every schema

**Comment by zhandao** [comment]
OK, I'll do this in a few hours.

**Comment by zhandao** [comment]
Done. Try the latest version 2.1.3.

**Comment by remuspoienar** [comment]
Works great. Thanks so much !
