### ISSUE TITLE
Is there anything I should be careful of when I use devise together?

### ISSUE THREAD

**Issue by spb829** [zhandao/zero-rails_openapi#63]
Hi!

I was googling around for OAS 3.0 gems like this gem.
Thanks for writing such library!

I really want to try it but suddemly I got a problem.
The error appears when I try to do `rails c` or run a server by `rails s`

Here is the infomation.
<details>
<summary>Traceback</summary>
<pre>
Traceback (most recent call last):
        112: from bin/rails:4:in `<main>'
        111: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        110: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        109: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        108: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        107: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        106: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        105: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        104: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        103: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
        102: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
        101: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
        100: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
         99: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         98: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         97: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/console/console_command.rb:101:in `perform'
         96: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
         95: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command/actions.rb:28:in `require_environment!'
         94: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/application.rb:339:in `require_environment!'
         93: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
         92: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
         91: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
         90: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
         89: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         88: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         87: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         86: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         85: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         84: from /mnt/c/Users/spb82/Documents/GitHub/api.main/config/environment.rb:5:in `<main>'
         83: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
         82: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
         81: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
         80: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
         79: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
         78: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `call'
         77: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each'
         76: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
         75: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
         74: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:415:in `call'
         73: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
         72: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
         71: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
         70: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
         69: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
         68: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
         67: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
         66: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
         65: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
         64: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
         63: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/engine.rb:623:in `block in <class:Engine>'
         62: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/engine.rb:623:in `each'
         61: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
         60: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/engine.rb:666:in `load_config_initializer'
         59: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:182:in `instrument'
         58: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/engine.rb:667:in `block in load_config_initializer'
         57: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:319:in `load'
         56: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
         55: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:319:in `block in load'
         54: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
         53: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
         52: from /mnt/c/Users/spb82/Documents/GitHub/api.main/config/initializers/open_api.rb:14:in `<main>'
         51: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api.rb:17:in `write_docs'
         50: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api.rb:29:in `generate_docs'
         49: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api.rb:63:in `traverse_controllers'
         48: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api.rb:63:in `each'
         47: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api.rb:64:in `block in traverse_controllers'
         46: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
         45: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/inflector/methods.rb:280:in `constantize'
         44: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/inflector/methods.rb:280:in `inject'
         43: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/inflector/methods.rb:280:in `each'
         42: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/inflector/methods.rb:284:in `block in constantize'
         41: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/inflector/methods.rb:284:in `const_get'
         40: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:214:in `const_missing'
         39: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
         38: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
         37: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
         36: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:545:in `load_missing_constant'
         35: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
         34: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
         33: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
         32: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:390:in `require_or_load'
         31: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:40:in `load_interlock'
         30: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
         29: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
         28: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
         27: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:40:in `block in load_interlock'
         26: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:407:in `block in require_or_load'
         25: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:510:in `load_file'
         24: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:702:in `new_constants_in'
         23: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:511:in `block in load_file'
         22: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
         21: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
         20: from /mnt/c/Users/spb82/Documents/GitHub/api.main/app/controllers/v2/answers_controller.rb:1:in `<main>'
         19: from /mnt/c/Users/spb82/Documents/GitHub/api.main/app/controllers/v2/answers_controller.rb:7:in `<module:V2>'
         18: from /mnt/c/Users/spb82/Documents/GitHub/api.main/app/controllers/v2/answers_controller.rb:10:in `<class:AnswersController>'
         17: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api/dsl.rb:36:in `api'
         16: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api/router.rb:28:in `routes_list'
         15: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zero-rails_openapi-2.1.4/lib/open_api/router.rb:14:in `routes'
         14: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
         13: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:289:in `load_dependency'
         12: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:702:in `new_constants_in'
         11: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:289:in `block in load_dependency'
         10: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
          9: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
          8: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
          7: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
          6: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
          5: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
          4: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
          3: from /mnt/c/Users/spb82/Documents/GitHub/api.main/config/routes.rb:1:in `<main>'
          2: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:412:in `draw'
          1: from /home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.1/lib/devise/rails/routes.rb:19:in `finalize!'
/home/eric/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/devise-4.7.1/lib/devise.rb:473:in `configure_warden!': undefined method `failure_app=' for nil:NilClass (NoMethodError)
</pre>
</details>

<details>
<summary>config/application.rb</summary>
<pre>
require_relative 'boot'

require "rails"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_view/railtie"

Bundler.require(*Rails.groups)

module BaseAPI
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 6.0

    config.api_only = true

    # Internationalization
    I18n.available_locales = [:en, :ko]
    config.encoding = "utf-8"
    config.time_zone = "Seoul"
    config.i18n.default_locale = :ko

    # Annotations
    config.annotations.register_directories("engines")
    config.annotations.register_tags("TESTME")
  end
end
</pre>
</details>

<details>
<summary>config/initializers/open_api.rb</summary>
<pre>
require 'open_api'

OpenApi::Config.class_eval do
  self.file_output_path = './'

  open_api :some_api, base_doc_classes: [V1::BaseController]
  info version: '1.0.0', title: 'API', description: "API"
end

OpenApi.write_docs if: !Rails.env.production?
</pre>
</details>

<details>
<summary>config/routes.rb</summary>
<pre>
Rails.application.routes.draw do
  namespace :v1, defaults: { format: :json } do
    resources :achievements do
    end
    resources :answers do
    end
    resources :boards do
      member do
        get :posts
      end
    end
    resources :branches do
    end
    resources :categories do
    end

    . . . 

    resources :themes do
    end
    resources :tokens do
    end
    resources :topics do
      member do
        get :super_themes
      end
    end
    resources :variables do
    end
    resources :view_types do
    end
  end
end
</pre>
</details>

<details>
<summary>Gemfile</summary>
<pre>
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'rails', '\~> 6.0.2'
gem 'puma', '~> 4.3'
gem 'bootsnap', '>= 1.4.5', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.1.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'rack-attack' # https://github.com/kickstarter/rack-attack
gem 'rack-cors' # https://github.com/cyu/rack-cors
gem 'config' # https://github.com/railsconfig/config
gem 'jwt' # https://github.com/jwt/ruby-jwt
gem 'mysql2'
gem 'fast_jsonapi' # https://github.com/Netflix/fast_jsonapi
gem 'rails-i18n', '\~> 6.0.0'
gem "globalize", "\~> 5.3.0"
gem "enumerize", "\~> 2.3.0"
gem "fast_jsonapi", "\~> 1.5.0"
gem "devise"
gem "google-api-client", "\~> 0.36"
gem 'pagy', '\~> 3.7.0'  # https://github.com/ddnexus/pagy
gem "aws-sdk-s3", require: false
gem 'zero-rails_openapi' # https://github.com/zhandao/zero-rails_openapi/
</pre>
</details>

I think there is nothing special in my code. so I wonder there is anything I shoud be careful of using devise gem together.
I will appreciate for any help. :)

**Comment by zhandao** [comment]
Hi,

Please run these two pieces of code in the rails console without requiring this gem:

```ruby
require './config/routes'
```

and

```ruby
Dir['./app/controllers/**/*_controller.rb'].each do |file|
  file.sub('./app/controllers/', '').sub('.rb', '').camelize.constantize
end
```

**Comment by spb829** [comment]
Thank you for the answering.
Did I miss somthing?
I removed this 'zero_rails-openapi' in gemfile then did `bundle` before run `rails console`

Here is the result.
<pre>
Loading development environment (Rails 6.0.2.1)
irb(main):001:0> require './config/routes'
=> true
irb(main):002:1* Dir['./app/controllers/**/*_controller.rb'].each do |file|
irb(main):003:1*   file.sub('./app/controllers/', '').sub('.rb', '').camelize.constantize
irb(main):004:0> end
=> ["./app/controllers/application_controller.rb", "./app/controllers/v1/achievements_controller.rb", "./app/controllers/v1/answers_controller.rb", "./app/controllers/v1/base_controller.rb", "./app/controllers/v1/boards_controller.rb", "./app/controllers/v1/branches_controller.rb", "./app/controllers/v1/categories_controller.rb", "./app/controllers/v1/chat_messages_controller.rb", "./app/controllers/v1/chat_rooms_controller.rb", "./app/controllers/v1/comments_controller.rb", "./app/controllers/v1/conditions_controller.rb", "./app/controllers/v1/events_controller.rb", "./app/controllers/v1/expressions_controller.rb", "./app/controllers/v1/genres_controller.rb", "./app/controllers/v1/hints_controller.rb", "./app/controllers/v1/inventories_controller.rb", "./app/controllers/v1/items_controller.rb", "./app/controllers/v1/locations_controller.rb", "./app/controllers/v1/main_controller.rb", "./app/controllers/v1/makers_controller.rb", "./app/controllers/v1/maker_teams_controller.rb", "./app/controllers/v1/plays_controller.rb", "./app/controllers/v1/posts_controller.rb", "./app/controllers/v1/ranks_controller.rb", "./app/controllers/v1/rank_seasons_controller.rb", "./app/controllers/v1/reviews_controller.rb", "./app/controllers/v1/settings_controller.rb", "./app/controllers/v1/stages_controller.rb", "./app/controllers/v1/stage_lists_controller.rb", "./app/controllers/v1/stage_list_types_controller.rb", "./app/controllers/v1/super_plays_controller.rb", "./app/controllers/v1/super_themes_controller.rb", "./app/controllers/v1/teams_controller.rb", "./app/controllers/v1/test_controller.rb", "./app/controllers/v1/themes_controller.rb", "./app/controllers/v1/tokens_controller.rb", "./app/controllers/v1/topics_controller.rb", "./app/controllers/v1/variables_controller.rb", "./app/controllers/v1/view_types_controller.rb", "./app/controllers/v2/answers_controller.rb", "./app/controllers/v2/base_controller.rb"]
irb(main):005:0>
</pre>

**Comment by zhandao** [comment]
Sorry, I haven't used devise, so I can't find the problem through the error stack you provided.

Could you try debugging to find out why the error `undefined method `failure_app=' for nil:NilClass (NoMethodError)` occurs?

**Comment by spb829** [comment]
Okay. I’ll try to find out.
Thanks for your help anyway! :)

**Comment by zhandao** [comment]
Hi, has the problem been solved?

**Comment by spb829** [comment]
Sorry for the late reply.
I've tried several possible solutions but no...
Thank you for your attension anyway :)
