### ISSUE TITLE
Looking for a Rails 4 example!

### ISSUE THREAD

**Issue by epugh** [zhandao/zero-rails_openapi#64]
I've found a lot of not great Swagger/Rails gems, so excited that this is OAS 3.0 compliant!

I followed the install step and am getting:

```
14:20:55 web.1    | [7] ! Unable to load application: NameError: uninitialized constant ApiDoc
14:20:55 worker.1 | uninitialized constant ApiDoc
14:20:55 worker.1 | /srv/app/config/initializers/01_open_api.rb:9:in `block in <top (required)>'
```

This is following this step: https://github.com/zhandao/zero-rails_openapi#configure

**Comment by zhandao** [comment]
Hi, You should replace `ApiDoc` with the base class of the classes you write spec documentation in.

**Comment by epugh** [comment]
Thanks, I got confused cause I saw in the Gem a `ApiDoc` as well.   Changing it to:

```
open_api :doc_name, base_doc_classes: [Api::ApiController]
```
Worked great.   

I had to manually run `rails c` and then run the command to output the docs.:

```
root@9d615e06ccac:/srv/app# rails c
Running via Spring preloader in process 24
Loading development environment (Rails 4.2.11)
irb(main):001:0> OpenApi.write_docs
    OpenApi loaded
    OpenApi `doc_name.json` has been generated.
=> {:doc_name=>{:openapi=>"3.0.0", :info=>{:version=>"1.0.0", :title=>"Quepid APIs", :description=>""}, :security=>[], :tags=>[], :paths=>{}, :components=>{}}}

```

Two questions:
1) Is there a way to have this be run on startup?  I see https://github.com/zhandao/zero-rails_openapi#run---generate-json-documentation-file and that suggests maybe adding this command to the initializer?   Or should there be a rake task?

2) Right now I get a template `./public/open_api/doc_name.json`, how do I get all the controllers that inherit from my `Api::ApiController` to be documented?

**Comment by zhandao** [comment]
1. Yes, I just add that command to the initializer. Of course, you can also write a rake task.
2. This gem will automatically traverse all the subclasses of `Api::ApiController`, for generating spec documentation you define.

**Comment by epugh** [comment]
So, do I put the spec documentation in each controller then?   I guess I was expecting to someohw auto generate the docs from Rails...

**Comment by zhandao** [comment]
Yes, just like
```ruby
class Api::ExamplesController < ApiController
  api :update, 'POST update some thing' do
    path  :id, Integer
    query :token, String, desc: 'api token', length: 16
    form data: { phone: String }
  end
end
```
Have a try.
