### ISSUE TITLE
Duplicate tags

### ISSUE THREAD

**Issue by luisl97** [zhandao/zero-rails_openapi#67]
I want to group multiple controllers under the same doc_tag.

I gave them the same `doc_tag name: Resource` and when I generate the doc I end up with: 

```
"tags": [

    {

      "name": "Resource"

    },

    {

      "name": "Resource"

    },

    {

      "name": "Resource"

    },

    {

      "name": "Resource"

    }
```

How should I be grouping multiple controllers under a single tag?

**Comment by zhandao** [comment]
I'm sorry it took so long to reply. Have you solved the problem?

**Comment by luisl97** [comment]
We've just had to manually remove the duplicates anytime documentation is regenerated.
