### ISSUE TITLE
Response schema validator

### ISSUE THREAD

**Issue by biske** [zhandao/zero-rails_openapi#69]
Hi,
I investigated openapi3 gems and seems like this one is doing a good job.
I wonder if there is an option to validate that response data in the test is in line with the response schema defined in the controller.

Ideally in request specs to have the ability to write something like this:
```
it 'validates response schema' do
  get '/api/v1/users'
  validate_response_schema(response_body: response.body, controller_action_for_which_we_are_validating_schema: 'users#index')
end
```
Of course, this code could be simplified but added for readability and to express intention.

Is there such a feature in this gem or is it planned? Any kind of direction is helpful.

**Comment by zhandao** [comment]
Sorry, this gem doesn't provide this feature.

You can search "rspec openapi" to find out if any gem can do this.  
This one looks ok: https://github.com/ketiko/open_api-rspec

**Comment by biske** [comment]
Thanks for the clarification.
